### ISSUE TITLE
Dear ObelusPA

### ISSUE THREAD

**Issue by RoboMWM** [MLG-Fortress/CreativeParkour#1]
@ObelusPA

Please re-enable issues so I can read the issues and instead set the repo to read-only (archive the repo in the settings).

Also, if you have a copy of the website/can publish it in a repo that'd be great so at least we can still get a copy of the uploaded maps without having to do a klutzy mirror of the site. Thanks!

**Comment by ObelusPA** [comment]
Hi, I re-enabled issues and published a copy of the website here: https://github.com/ObelusPA/CreativeParkour-website

The code is a huge mess, I am sorry for this. You can find maps and ghosts in "[maps data](https://github.com/ObelusPA/CreativeParkour-website/tree/master/maps%20data)", there is also some data in the included database.

**Comment by RoboMWM** [comment]
Thank you! And yes I already knew it was a mess c:

But I haven't seen anything like this before, especially not open source (except for PlotSquared I guess). So thank you regardless!
